baseURL = 'https://whimsical-macaron-cef883.netlify.app/' # Netlify will update this automatically later
languageCode = 'en-us'
title = 'CyberSyncIT News'
theme = 'anubis'

[params]
  description = 'Daily insights into the evolving landscape of cybersecurity.'
  social: {
    github = 'https://github.com/wolmarsh'
  }

