baseURL = 'https://wolmarsh.github.io/news/'
languageCode = 'en-us'
title = 'CyberSyncIT News'
theme = 'PaperMod'

[params]
  description = 'Daily insights into the evolving landscape of cybersecurity.'
  title = 'CyberSyncIT News'
  customCSS = ["css/custom.css"]
  
[[params.social]]
id = "github"
url = "https://github.com/wolmarsh"

