baseURL = 'https://whimsical-macaron-cef883.netlify.app/'
languageCode = 'en-us'
title = 'CyberSyncIT News'
theme = 'PaperMod'

[params]
  description = 'Daily insights into the evolving landscape of cybersecurity.'
  title = 'CyberSyncIT News'
  
[[params.social]]
id = "github"
url = "https://github.com/wolmarsh"

